// Mocks generated by Mockito 5.4.2 from annotations
// in pokemon/test/features/all_pokemons/data/repositories/pokemon_list_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pokemon/features/all_pokemons/data/dataSources/pokemon_list_remote_data_source.dart'
    as _i3;
import 'package:pokemon/features/all_pokemons/data/models/pokemon_list_req_model.dart'
    as _i5;
import 'package:pokemon/features/all_pokemons/data/models/pokemon_list_resp_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokemonListRespModel_0 extends _i1.SmartFake
    implements _i2.PokemonListRespModel {
  _FakePokemonListRespModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PokemonListRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonListRemoteDataSource extends _i1.Mock
    implements _i3.PokemonListRemoteDataSource {
  MockPokemonListRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PokemonListRespModel> getPokemonList(
          {required _i5.PokemonListReqModel? pokemonListReqParamsModel}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonList,
          [],
          {#pokemonListReqParamsModel: pokemonListReqParamsModel},
        ),
        returnValue: _i4.Future<_i2.PokemonListRespModel>.value(
            _FakePokemonListRespModel_0(
          this,
          Invocation.method(
            #getPokemonList,
            [],
            {#pokemonListReqParamsModel: pokemonListReqParamsModel},
          ),
        )),
      ) as _i4.Future<_i2.PokemonListRespModel>);
}
